# Refinex Terminal — rustfmt configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"

# Formatting style
use_small_heuristics = "Default"
newline_style = "Unix"
trailing_comma = "Vertical"
trailing_semicolon = true
force_multiline_blocks = false

# Comments
comment_width = 100
wrap_comments = true
normalize_comments = true

# Misc
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
merge_derives = true
use_field_init_shorthand = true
